// 无头浏览器回归：使用真实组件和隔离样例库，保存截图，不打开窗口或发送微信消息。
const { parseArgs } = require('node:util')
const fs = require('node:fs/promises')
const path = require('node:path')
const { values } = parseArgs({options:{output:{type:'string'},playwright:{type:'string'},browser:{type:'string'},fixture:{type:'string',default:'http://127.0.0.1:3050/tests/fixtures/agent-redesign.html'},app:{type:'string',default:'http://127.0.0.1:10492'}}})
if (!values.output) throw new Error('请指定新的截图及记录目录 --output')
const { chromium } = require(values.playwright || 'playwright')
const assert = require('node:assert/strict')
const output = path.resolve(values.output)
async function main() {
  await fs.mkdir(output, {recursive:false})
  const browser = await chromium.launch({headless:true,...(values.browser?{executablePath:values.browser}:{})})
  const page = await browser.newPage({viewport:{width:1280,height:800},locale:'zh-CN'})
  const result = {mode:'headless_browser_synthetic_data',started:new Date().toISOString(),remote_model_calls:0,checks:[],errors:[]}
  page.on('pageerror', error=>result.errors.push(error.message))
  const capture = async name=>{await page.screenshot({path:path.join(output,name+'.png')}); result.checks.push(name)}
  try {
    await page.goto(values.fixture)
    await page.getByLabel('调整 AI 助手宽度').press('Home')
    const dimensions = await page.locator('.agent-panel').evaluate(panel=>{
      const ring=panel.querySelector('.agent-context-ring svg'),button=panel.querySelector('.agent-send')
      return {panel:panel.getBoundingClientRect().width,overflow:panel.scrollWidth-panel.clientWidth,ring:ring.getBoundingClientRect().width,button:button.getBoundingClientRect().width}
    })
    assert.equal(Math.round(dimensions.panel),320)
    assert.equal(dimensions.overflow,0)
    assert.equal(dimensions.ring,10)
    assert.equal(dimensions.button,28)
    result.dimensions=dimensions
    await capture('d01-sidebar-light')
    const source=page.locator('.agent-final-answer').getByLabel('查看来源 1',{exact:true})
    await source.hover()
    await page.getByRole('dialog',{name:'消息来源预览'}).waitFor()
    await source.click()
    await page.mouse.move(50,50)
    await page.getByRole('dialog',{name:'消息来源预览'}).waitFor()
    await capture('d03-source-pinned')
    await page.getByLabel('关闭来源预览').click()
    await page.getByRole('button',{name:'深色',exact:true}).click()
    await page.getByLabel('给 AI 助手的消息').fill('中文草稿，尚未提交')
    await page.getByLabel('选择服务配置与模型').click()
    await capture('d01-sidebar-dark-models')
    await page.getByLabel('选择服务配置与模型').press('Escape')
    await page.getByLabel('展开大视图').click()
    await capture('d02-expanded-dark')
    await page.goto(values.fixture+'?references=1')
    await page.getByRole('button',{name:'排期示意图',exact:true}).click()
    const picture=page.locator('.agent-image-stage img')
    await picture.waitFor()
    await picture.evaluate(img=>img.decode())
    await capture('d04-image-light')
    await page.getByLabel('放大图片').click()
    await page.getByLabel('旋转图片').click()
    assert.match(await picture.getAttribute('style'),/rotate\(90deg\).*scale\(1.25\)/)
    await page.getByLabel('复位图片').click()
    assert.match(await picture.getAttribute('style'),/rotate\(0deg\).*scale\(1\)/)
    await page.getByLabel('下一张图片').click()
    await page.getByText('图片暂不可用，可定位原消息核对。').waitFor()
    assert.match(await page.locator('.agent-image-viewer').textContent(),/图片 2 \/ 2/)
    assert.doesNotMatch(await page.locator('.agent-image-viewer').textContent(),/未引用图片/)
    await capture('d04-image-missing')
    await page.getByLabel('关闭图片查看器').click()
    await page.getByRole('button',{name:'深色',exact:true}).click()
    await page.getByRole('button',{name:'排期示意图',exact:true}).click()
    await capture('d04-image-dark')

    await page.goto(values.app+'/chat')
    const agree=page.getByRole('button',{name:'我已阅读全部内容并同意',exact:true})
    await agree.click({timeout:35000})
    await page.getByRole('heading',{name:'验收 · 海桥项目',exact:true,level:2}).waitFor()
    await page.getByLabel('AI 助手',{exact:true}).click()
    await page.getByLabel('给 AI 助手的消息').fill('跨群检索草稿保持')
    await page.getByRole('heading',{name:'验收 · 小林',exact:true,level:3}).click()
    assert.equal(await page.getByLabel('给 AI 助手的消息').inputValue(),'跨群检索草稿保持')
    await capture('app-chat-switch-draft')
    await page.getByLabel('更多 AI 功能').click()
    await page.getByRole('button',{name:'工具与任务',exact:true}).click()
    await page.getByText('关注提醒',{exact:true}).waitFor()
    await capture('app-existing-tools')
    await page.goto(values.app+'/sns')
    await page.getByText('本地验收示例：今天已完成排期确认，接下来核对交付内容。',{exact:true}).waitFor()
    await capture('app-moments')
    await page.goto(values.app+'/chat')
    await page.getByLabel('AI 助手',{exact:true}).click()
    await page.getByLabel('更多 AI 功能').click()
    await page.getByRole('button',{name:'AI 服务设置',exact:true}).click()
    await page.getByText('AI 服务',{exact:true}).first().waitFor()
    await capture('app-ai-settings')
    assert.deepEqual(result.errors,[])
    result.passed=true
  } catch(error) {
    result.passed=false; result.failure=error.stack
    await page.screenshot({path:path.join(output,'failure.png')}).catch(()=>{})
    process.exitCode=1
  } finally {
    await fs.writeFile(path.join(output,'result.json'),JSON.stringify(result,null,2))
    await browser.close()
    console.log(JSON.stringify(result,null,2))
  }
}
main().catch(error=>{console.error(error);process.exitCode=1})
